### ISSUE TITLE
Unable to reclaim released drives because "unrelease" is deprecated

### ISSUE THREAD

**Issue by blampe** [minio/directpv#596]
After releasing a drive, if you try to format it to make it available again the command will fail. It tries to helpfully suggest some commands to remedy the situation, but unfortunately those don't work, either.

```
❯ kubectl krew list
PLUGIN    VERSION
directpv  v3.0.1
minio     v4.4.21
```

```
❯ kubectl directpv drives format --all --force
E0603 20:07:27.380997   95883 drives_format.go:132] n1:/dev/sda is in 'released' state. Use 'kubectl directpv drives unrelease --drive sda --nodes n1’ before formatting
E0603 20:07:27.381215   95883 drives_format.go:132] n2:/dev/sda is in 'released' state. Use 'kubectl directpv drives unrelease --drive sda --nodes n2’ before formatting
E0603 20:07:27.381291   95883 drives_format.go:132] n3:/dev/sda is in 'released' state. Use 'kubectl directpv drives unrelease --drive sda --nodes n3’ before formatting

❯ kubectl directpv drives unrelease --drive sda --nodes n1
Command "unrelease" is deprecated, please use `kubectl directpv drives release` which will umount and make the drives `Available`
Error: unknown flag: --drive
ERROR unknown flag: --drive

❯ kubectl directpv drives release —nodes n1
E0603 20:07:52.417994   95935 drives_release.go:114] n1:/dev/sda already in 'released' state
```

I tried to nudge directpv to re-scan the drives by deleting the relevant `directcsidrives.direct.csi.min.io` resources, but that only put it into a never-ending loop of these errors (event after removing and re-installing directpv!):
```
directpv-drive-discovery E0604 03:32:43.509129  173072 listener.go:206] "failed to handle an event" err="Operation cannot be fulfilled on directcsidrives.direct.csi.min.io \"7ba2beab-877f-ad8e-e621-508f1c5a762f\": the object has been modified; please apply your changes to the latest version and try again" sync="(MISSING)"
```
Ultimately I was able to work around this by rebooting the nodes.

**Comment by Praveenrajmani** [comment]
The `kubectl directpv drives release` command should release the "Ready" drive and make it "Available".

> I tried to nudge directpv to re-scan the drives by deleting the relevant directcsidrives.direct.csi.min.io resources, but that only put it into a never-ending loop of these errors (event after removing and re-installing directpv!):

you shouldn't try to manually edit or remove the directpv resources

> directpv-drive-discovery E0604 03:32:43.509129  173072 listener.go:206] "failed to handle an event" err="Operation cannot be fulfilled on directcsidrives.direct.csi.min.io \"7ba2beab-877f-ad8e-e621-508f1c5a762f\": the object has been modified; please apply your changes to the latest version and try again" sync="(MISSING)"

these errors arise due to conflict, which are usual. DirectPV will internally retry these APIs.

> Ultimately I was able to work around this by rebooting the nodes.

If it is not moving to "Available" state after executing the "kubectl directpv drives release" command, the drive controller should have stopped due to some reason (one such reason is stated in https://github.com/minio/directpv/issues/595), In these cases, only restarting the directpv pod would restart the drive and volume controller. Looks like the workaround helped here to restart the drive controller

If you see this next time, please paste the logs here. `kubectl logs <pod-name> -n direct-csi-min-io direct-csi` from the corresponding node should give the logs that we needed.

closing this issue, please feel free to re-open with some logs if you see this again.
