### ISSUE TITLE
behaviour when the node is lost

### ISSUE THREAD

**Issue by pchovgh** [minio/directpv#743]
Hello,

This link [https://hub.docker.com/r/minio/direct-csi](url) states the below:

> The high consistency and performance benefits of DirectCSI come with the limitation that once provisioned, volumes cannot be moved to other nodes i.e. volumes are sticky to nodes. In case a node is lost, then the volume is also lost.

We understand that the volume will be lost if a node goes down. Can you help understand what exactly will happen in such a situation? Will the PVC cease to exist OR will the PVC stay which means that the application pod will wait forever for the PV to be available?

Thanks

**Comment by balamurugana** [comment]
If a node goes down, associated volumes do not available and respective pods will be waiting forever for PVs to be available.  Your application supposes to take care of this situation. In case of MinIO server, this situation is handled gracefully and other redundant volumes/pods still serve the data due to erasure coding.
